webserver:
  port: 10140
  host: 0.0.0.0
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

data-access:
  provider: no.ssb.dapla.data.access.service.GoogleDataAccessService

catalog-service:
  host: localhost
  port: 20110

auth-service:
  host: localhost
  port: 10100

tracing:
  enabled: true
  service: data-access
  sampler-type: const
  sampler-param: 1
  propagation: b3
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/metrics/vendor"
      enabled: false
    - path: "/metrics/base"
      enabled: false
    - path: "/metrics/application"
      enabled: false
    - path: "/health"
      enabled: false
    - path: "/health/live"
      enabled: false
    - path: "/health/ready"
      enabled: false

metadatads:
  format: PKCS12
  keystore: secret/metadata-signer_keystore.p12
  keyAlias: dataAccessKeyPair
  password: changeit
  algorithm: SHA256withRSA

routing:
  file: /conf/routing.json

token:
  lifetime: 28800
