webserver:
  port: 10140
  host: 0.0.0.0
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

data-access:
  provider: no.ssb.dapla.data.access.service.GoogleDataAccessService

grpcserver:
  host: 0.0.0.0
  port: 10148

catalog-service:
  host: localhost
  port: 10118

auth-service:
  host: localhost
  port: 10108

tracing:
  enabled: true
  service: data-access
  sampler-type: const
  sampler-param: 1
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/health"
      enabled: false

metadatads:
  signer:
    format: PKCS12
    keystore: secret/metadata-signer_keystore.p12
    keyAlias: dataAccessKeyPair
    password: changeit
    algorithm: SHA256withRSA
  verifier:
    format: PKCS12
    keystore: secret/metadata-verifier_keystore.p12
    keyAlias: dataAccessCertificate
    password: changeit
    algorithm: SHA256withRSA
