webserver:
  port: 10130
  host: 0.0.0.0
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

grpcserver:
  host: 0.0.0.0
  port: 10138

tracing:
  enabled: true
  service: data-access
  sampler-type: const
  sampler-param: 1
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/health"
      enabled: false
